# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SdatToTif
                                 A QGIS plugin
 Sdat to Tif
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-21
        copyright            : (C) 2020 by David Gauthier MFFP
        email                : david.gauthier@mffp.gouv.qc.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'David Gauthier MFFP'
__date__ = '2020-07-21'
__copyright__ = '(C) 2020 by David Gauthier MFFP'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SdatToTif class from file SdatToTif.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Sdat_to_Tif import SdatToTifPlugin
    return SdatToTifPlugin()
