# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TransferLayerFileGdbToGeoPackage
                                 A QGIS plugin
 Transferer des couches provenant dune file Geodatabase de ESRI dans un GeoPackage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-30
        copyright            : (C) 2020 by David Gauthier - MFFP (DIF)
        email                : david.gauthier@mffp.gouv.qc.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TransferLayerFileGdbToGeoPackage class from file TransferLayerFileGdbToGeoPackage.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Transfer_LayerFileGdb_To_GeoPackage import TransferLayerFileGdbToGeoPackage
    return TransferLayerFileGdbToGeoPackage(iface)
