# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sptialJoinLargestOverlap
                                 A QGIS plugin
 Join spatial permettant de recuperer les attributs ayant la plus grande proportion de superposition de la table ou classe d'entités join
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-21
        copyright            : (C) 2020 by David Gauthier MFFP,DIF
        email                : david.gauthier@mffp.gouv.qc.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'David Gauthier MFFP,DIF'
__date__ = '2020-08-21'
__copyright__ = '(C) 2020 by David Gauthier MFFP,DIF'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load sptialJoinLargestOverlap class from file sptialJoinLargestOverlap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sptialJoinLargestOverlap import sptialJoinLargestOverlapPlugin
    return sptialJoinLargestOverlapPlugin()
