# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CalculdesGeocodes
                                 A QGIS plugin
 Permet de calculer des GEOCODE
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-04-05
        copyright            : (C) 2020 by David Gauthier - MFFP (DIF)
        email                : david.gauthier@mffp.gouv.qc.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'David Gauthier - MFFP (DIF)'
__date__ = '2020-04-05'
__copyright__ = '(C) 2020 by David Gauthier - MFFP (DIF)'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import *
from QGIS_commun import calculGeocode


class CalculdesGeocodesAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    INPUT_ce = 'INPUT_ce'
    champ = 'champ'
    whereClause = 'whereClause'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.addParameter(QgsProcessingParameterFeatureSource(self.INPUT_ce, self.tr('Couche en entrée'),
                                                [QgsProcessing.TypeVectorAnyGeometry]))


        self.addParameter(QgsProcessingParameterField(self.champ, self.tr('Choix du champ (GEOCODE, GEOC_FOR, GEOC_MAJ, etc...)'),
                                                      parentLayerParameterName=self.INPUT_ce,
                                                     defaultValue='GEOCODE',
                                                     optional=False))

        self.addParameter(QgsProcessingParameterExpression(self.whereClause, self.tr('Requête SQL'),
                                                           parentLayerParameterName=self.INPUT_ce, optional=True))

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        # Parametres
        ce = self.parameterAsVectorLayer(parameters,  self.INPUT_ce, context)
        champ = self.parameterAsString(parameters, self.champ, context)
        whereClause = self.parameterAsString(parameters, self.whereClause, context)

        calculGeocode(ce, champ, whereClause)

        return {self.INPUT_ce: 'Calcul terminé'}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Calcul des GEOCODE'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CalculdesGeocodesAlgorithm()
