# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CreationplacetteMesurable
                                 A QGIS plugin
 Confection de plans de sondage - DIF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-13
        copyright            : (C) 2021 by MFFP - DIF
        email                : david.gauthier@mffp.gouv.qc.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'MFFP - DIF'
__date__ = '2021-07-13'
__copyright__ = '(C) 2021 by MFFP - DIF'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import *
import os
import processing
from processing.tools import dataobjects
from qgis.PyQt.QtGui import QIcon
import line_profiler
import geopandas as gpd
import subprocess
from os import sys

profile = line_profiler.LineProfiler()

def copyCeToGpkg(ce, gpkg, nomCouche):

    # faire un layer avec la string ce
    couche = QgsVectorLayer(ce, "lyr", 'ogr')

    # Option de sauvegarde
    options = QgsVectorFileWriter.SaveVectorOptions()

    # J'enleve l'extension
    gpkg = gpkg.replace(".gpkg", "")

    options.driverName = 'GPKG'
    options.layerName = nomCouche

    # Transférer la ce de la gdb vers le GeoPackage
    QgsVectorFileWriter.writeAsVectorFormat(couche, gpkg, options)

    sortie = gpkg + ".gpkg" + '|' + 'layername=' + nomCouche

    return sortie



def dissolvedGeopandasGPKG(gpkg, namefc, nameoutfc, fields = None):

    """
    Permet de faire un dissolve avec Geopandas dans un geopackage
    Geopandas ne gere pas encore les valeur Null lors du dissole. C'est pour ca que je rempli
    les valeurs Null pas une string "null"

              Args:
                  gpkg : geopackage
                  namefc : nom de la classe d'entité
                  nameoutfc : nom de la classe d'entité en sortie
                  fields : champ



              Exemple d'appel de la fonction:

              gpkg = r"C:\MrnMicro\temp\test_dissolve_fiona\HISTO_MAJF_2018.gpkg"
              ce ='HISTO_MAJF_2018_Repair'
              out = 'HISTO_MAJF_2018_diss'
              fields = 'CO_TER'


              dissolvedGeopandasGPKG(gpkg, ce, out, fields)


       """

    if fields is None:
        layer = gpd.read_file(gpkg, layer=namefc)
        gdfu = layer.unary_union
        new = gpd.GeoDataFrame(crs=layer.crs, geometry=[gdfu])
        new.to_file(gpkg, layer=nameoutfc, driver="GPKG")

    else:
        layer = gpd.read_file(gpkg, layer=namefc)
        filled = layer.fillna('null')
        dissolved = filled.dissolve(by=fields, aggfunc = 'last', as_index=False)
        dissolved.to_file(gpkg, layer=nameoutfc, driver="GPKG")


class PreparationIntrantsAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    UniteSondage = 'UniteSondage'
    uniteSondage = 'uniteSondage'
    DossierIntrants = 'DossierIntrants'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # Unité de sondage (CE)
        self.addParameter(QgsProcessingParameterFeatureSource(self.UniteSondage, self.tr('Unité de sondage en entrée'),
                                                              [QgsProcessing.TypeVectorAnyGeometry]))

        # parametre de l'unité de sondage
        self.addParameter(
            QgsProcessingParameterString(
                self.uniteSondage,
                ('Unité de sondage'),
                defaultValue="1415CE",
                optional=False)
        )


        # Parametre Dossier Intrants
        self.addParameter(QgsProcessingParameterFile
                          (self.DossierIntrants,'Dossier des intrants',
                                                     behavior=QgsProcessingParameterFile.Folder,
                                                     defaultValue=None))



    @profile
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        feedback.pushInfo("\nDébut du processus\n")


        # unité de sondage
        path_us = self.parameterAsVectorLayer(parameters,  self.UniteSondage, context)

        # numéro de l'unité de sondage
        us = self.parameterAsString(parameters, self.uniteSondage, context)

        # Parametres Dossier Intrants
        wd_intrants = self.parameterAsString(parameters,  self.DossierIntrants, context)



        feedback.pushInfo("\nVous traité l'unité de sondage : {0}\n".format(us))

        # Permet d'ignorer les erreurs de geometries
        noCheckGeom = dataobjects.createContext()
        noCheckGeom.setInvalidGeometryCheck(QgsFeatureRequest.GeometryNoCheck)


        # Liste des intrants sur le réseau (DDE et autres)

        # path_PeupForestiers_reseau =

        path_PentesNum_reseau = r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Classe_de_pente_numerique\CLASSES_DE_PENTE_NUMERIQUE_S\FGDB_GEO\CPN_PROV\CPN_PROV.gdb\CPN_PROV"

        path_HydroLin_reseau = r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Reference_geographique_Quebec\
                                BDTQ_20K_a_jour\HYDROGRAPHIE_LINEAIRE_BDTQ_20K_L\FGDB_GEO\HL20_PROV\HL20_PROV.gdb\BDTQ_20K_HYDRO_LO"

        path_VoieFerree_reseau = r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Reference_geographique_Quebec\
                                BDTQ_20K_a_jour\VOIE_COMM_LINEAIRE_BDTQ_20K_L\FGDB_GEO\VCL_BDTQ_20K\VCL_BDTQ_20K.gdb\BDTQ_20K_VOIE_COMMU_LO"

        path_PEP_reseau = r"\\vulcain\raigeop\Depot_Dde\Produits_IEQM\Placettes_echantillons\PEP.gpkg|layername=df_placettes_metadata_PeupForestiers_US"

        path_ponc_reseau = r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Reference_geographique_Quebec\
                                BDTQ_20K_a_jour\BATIMENT_PONCTUEL_BDTQ_20K_P\FGDB_GEO\BATP_PROV\BATP_PROV.gdb\BDTQ_20K_BATIM_PO"

        path_BatiLin_reseau=r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Reference_geographique_Quebec\
                                BDTQ_20K_a_jour\BATIMENT_LINEAIRE_BDTQ_20K_L\FGDB_GEO\BATL_PROV\BATL_PROV.gdb\BDTQ_20K_BATIM_LO"

        path_BatiSur_reseau=r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Reference_geographique_Quebec\
                                BDTQ_20K_a_jour\BATIMENT_SURFACIQUE_BDTQ_20K_S\FGDB_GEO\BATS_PROV\BATS_PROV.gdb\BDTQ_20K_BATIM_SO"

        path_EquipPonc_reseau=r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Reference_geographique_Quebec\
                                BDTQ_20K_a_jour\EQUIPEMENT_PONCTUEL_BDTQ_20K_P\FGDB_GEO\EQP_PROV\EQP_PROV.gdb\BDTQ_20K_EQUIP_PO"

        path_EquipLin_reseau=r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Reference_geographique_Quebec\
                                BDTQ_20K_a_jour\EQUIPEMENT_LINEAIRE_BDTQ_20K_L\FGDB_GEO\EQL_PROV\EQL_PROV.gdb\BDTQ_20K_EQUIP_LO"

        path_EquipSur_reseau=r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Reference_geographique_Quebec\
                                BDTQ_20K_a_jour\EQUIPEMENT_SURFACIQUE_BDTQ_20K_S\FGDB_GEO\EQS_PROV\EQS_PROV.gdb\BDTQ_20K_EQUIP_SO"


        path_AffecPonc_reseau=r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Utilisation_du_territoire\
                                Usage_forestier\USAGE_FORESTIER_PONCTUEL_P\FGDB_CCL\UFP_PROV\UFP_PROV.gdb\DDE_UFZ_USAGE_FORES_VUE_P"

        path_AffecLin_reseau=r"\\vulcain\raigeop\Depot_Dde\Catalogue_du_systeme_DDE\Couches_de_donnees\Utilisation_du_territoire\
                                Usage_forestier\USAGE_FORESTIER_LINEAIRE_L\FGDB_CCL\UFL_PROV\UFL_PROV.gdb\DDE_UFZ_USAGE_FORES_VUE_L"

        # path_Feux_reseau=
        # path_PertMaj_reseau=

        # path_Interv_reseau=
        # path_Planif_reseau=



        # # Liste des intrants local (shp)
        #
        # path_PeupForestiers = os.path.join(wd_intrants, "DDE_20K_PEU_FOR_ORI_TRV_VUE_SE_{0}.shp".format(us))#OUTIL
        # path_PentesNum      = os.path.join(wd_intrants, "DDE_20K_CLA_PEN_VUE_SE_{0}.shp".format(us))#OUTIL
        # path_HydroLin       = os.path.join(wd_intrants, "BDTQ_20K_HYDRO_LO_{0}.shp".format(us))# OUTIL
        # path_VoieFerree     = os.path.join(wd_intrants, "BDTQ_20K_VOIE_COMMU_LO_{0}.shp".format(us))# OUTIL
        # path_PEP            = os.path.join(wd_intrants, "DDE_20K_PEP_VUE_PE_{0}.shp".format(us))# OUTIL
        # path_ponc           = os.path.join(wd_intrants, "BDTQ_20K_BATIM_PO_{0}.shp".format(us))# OUTIL
        # path_BatiLin        = os.path.join(wd_intrants, "BDTQ_20K_BATIM_LO_{0}.shp".format(us))# OUTIL
        # path_BatiSur        = os.path.join(wd_intrants, "BDTQ_20K_BATIM_SO_{0}.shp".format(us))# OUTIL
        # path_EquipPonc      = os.path.join(wd_intrants, "BDTQ_20K_EQUIP_PO_{0}.shp".format(us))# OUTIL
        # path_EquipLin       = os.path.join(wd_intrants, "BDTQ_20K_EQUIP_LO_{0}.shp".format(us))# OUTIL
        # path_EquipSur       = os.path.join(wd_intrants, "BDTQ_20K_EQUIP_SO_{0}.shp".format(us))# OUTIL
        # path_AffecPonc      = os.path.join(wd_intrants, "DDE_UFZ_20K_USAGE_FOR_VUE_PE_{0}.shp".format(us))# OUTIL
        # path_AffecLin       = os.path.join(wd_intrants, "DDE_UFZ_20K_USAGE_FOR_VUE_LE_{0}.shp".format(us))# OUTIL
        # path_Feux           = os.path.join(wd_intrants, "DDE_20K_FEUX_MAJ_TRV_{0}.shp".format(us))# OUTIL
        # path_PertMaj        = os.path.join(wd_intrants, "DDE_20K_AUTRE_PERTU_MAJ_TRV_{0}.shp".format(us))# OUTIL
        # path_Interv         = os.path.join(wd_intrants, "INTERVENTION_{0}.shp".format(us))# YVAN
        # path_Planif         = os.path.join(wd_intrants, "PLAN_{0}.shp".format(us))# YVAN
        # path_BufferIn       = os.path.join(wd_intrants, "us_bufin_{0}_2025m.shp".format(us))# OUTIL


        # #Ce sont des intrants préparés hors de l'outil
        # path_us             = os.path.join(wd_intrants, "US_{0}.shp".format(us))  #Robin
        # path_ParamBuffers   = os.path.join(wd_intrants,  "Parametres", "BUFFER_template.csv")# SONDAGE
        # path_chemins        = os.path.join(wd_intrants, "CHEMIN_SONAR_{0}.shp".format(us)) # SONDAGE
        # path_geocodes       = os.path.join(wd_intrants, "LIST_GEOC_{0}.shp".format(us)) # PHILIPPE MORIN
        # path_masque         = os.path.join(wd_intrants, "MASQUE_{0}.shp".format(us))# SONDAGE
        # path_SIP            = os.path.join(wd_intrants, "CFETBFEC_08664_SIP.shp")# Pour l'intant on laisse desactivé


        # Liste des intrant local (gpkg)
        # gpkg des intrants
        gpkg = os.path.join(wd_intrants,"SONAR2_Intrants.gpkg")


        path_PeupForestiers = 'ogr:dbname=\'{0}\' table=\"DDE_20K_PEU_FOR_ORI_TRV_VUE_SE_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_PentesNum = 'ogr:dbname=\'{0}\' table=\"DDE_20K_CLA_PEN_VUE_SE_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_HydroLin = 'ogr:dbname=\'{0}\' table=\"BDTQ_20K_HYDRO_LO_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_VoieFerree = 'ogr:dbname=\'{0}\' table=\"BDTQ_20K_VOIE_COMMU_LO_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_PEP = 'ogr:dbname=\'{0}\' table=\"DDE_20K_PEP_VUE_PE_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_ponc = 'ogr:dbname=\'{0}\' table=\"BDTQ_20K_BATIM_PO_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_BatiLin = 'ogr:dbname=\'{0}\' table=\"BDTQ_20K_BATIM_LO_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_BatiSur = 'ogr:dbname=\'{0}\' table=\"BDTQ_20K_BATIM_SO_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_EquipPonc = 'ogr:dbname=\'{0}\' table=\"BDTQ_20K_EQUIP_PO_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_EquipLin = 'ogr:dbname=\'{0}\' table=\"BDTQ_20K_EQUIP_LO_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_EquipSur = 'ogr:dbname=\'{0}\' table=\"BDTQ_20K_EQUIP_SO_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_AffecPonc = 'ogr:dbname=\'{0}\' table=\"DDE_UFZ_20K_USAGE_FOR_VUE_PE_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_AffecLin = 'ogr:dbname=\'{0}\' table=\"DDE_UFZ_20K_USAGE_FOR_VUE_LE_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_Feux = 'ogr:dbname=\'{0}\' table=\"DDE_20K_FEUX_MAJ_TRV_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_PertMaj = 'ogr:dbname=\'{0}\' table=\"DDE_20K_AUTRE_PERTU_MAJ_TRV_{1}\" (geom) sql='.format(gpkg,us)#OUTIL
        path_Interv = 'ogr:dbname=\'{0}\' table=\"INTERVENTION_{1}\" (geom) sql='.format(gpkg,us)#YVAN
        path_Planif = 'ogr:dbname=\'{0}\' table=\"PLAN_{1}\" (geom) sql='.format(gpkg,us)#YVAN
        path_BufferIn = 'ogr:dbname=\'{0}\' table=\"us_bufin_{1}_2025m\" (geom) sql='.format(gpkg,us)#OUTIL


        # couches intermediaires
        path_us_dissolve = '{0}|layername=us_dissolve'.format(gpkg)
        path_us_buf_2km = '{0}|layername=us_buf_2km'.format(gpkg)

        # # copie l'us dans le geopackage
        # # Copie des peuplement dans le GPKG
        # us_gpkg = 'us'
        # copyCeToGpkg(path_us, gpkg, us_gpkg)

        # # faire un dissolve de l'US
        # dissolvedGeopandasGPKG(gpkg, us_gpkg, 'us_dissolve', fields = None)

        # faire un dissolve arcpy
        path_arpyPy = os.path.dirname(__file__) + '/Arcpy_Dissolve_SONAR2.py {}'.format(path_us)
        subprocess.call("C:\Mrnmicro\Applic\python27\ArcGIS10.3\python.exe"+ " "+ path_arpyPy)

        # supprimer les trous
        clean_us = processing.run("native:deleteholes", {'INPUT':path_us_dissolve,'MIN_AREA':0,
                                                         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT})["OUTPUT"]

        # faire la couche path_BufferIn



        # faire un buffer de 2000m de l'US
        processing.run("native:buffer", {'INPUT':clean_us,'DISTANCE':2000,'SEGMENTS':5,'END_CAP_STYLE':0,'JOIN_STYLE':0,'MITER_LIMIT':2,
                                         'DISSOLVE':False,'OUTPUT':path_us_buf_2km})

        # Faire les différents clip








        return {self.uniteSondage:us}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '0 - Préparation des intrants'

    def icon(self):
        return QIcon(os.path.dirname(__file__) + '/image/preparation.png')

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())


    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''


    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PreparationIntrantsAlgorithm()
