# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreationplacetteMesurable
                                 A QGIS plugin
 Confection de plans de sondage - DIF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-13
        copyright            : (C) 2021 by MFFP - DIF
        email                : david.gauthier@mffp.gouv.qc.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'MFFP - DIF'
__date__ = '2021-07-13'
__copyright__ = '(C) 2021 by MFFP - DIF'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreationplacetteMesurable class from file CreationplacetteMesurable.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SONAR2 import SONAR2Plugin
    return SONAR2Plugin()
